In [1]:
%pylab notebook
import numpy as np
import numpy.linalg as la
import pandas as pd

np.set_printoptions(suppress=True)


Populating the interactive namespace from numpy and matplotlib


In [2]:
def add_vertex(v):
  global graph
  global vertices_no
  global vertices
  if v in vertices:
    print("Vertex ", v, " already exists")
  else:
    vertices_no = vertices_no + 1
    vertices.append(v)
    if vertices_no > 1:
        for vertex in graph:
            vertex.append(0)
    temp = []
    for i in range(vertices_no):
        temp.append(0)
    graph.append(temp)


def add_edge(v1, v2, e):
    global graph
    global vertices_no
    global vertices
    
    if v1 not in vertices:
        print("Vertex ", v1, " does not exist.")
    
    elif v2 not in vertices:
        print("Vertex ", v2, " does not exist.")
    
    else:
        index1 = vertices.index(v1)
        index2 = vertices.index(v2)
        graph[index1][index2] = e


def print_graph():
  global graph
  global vertices_no
  for i in range(vertices_no):
    for j in range(vertices_no):
      if graph[i][j] != 0:
        print(vertices[i], " -> ", vertices[j], \
        " edge weight: ", graph[i][j])


vertices = []

vertices_no = 0
graph = []

add_vertex(1)
add_vertex(2)
add_vertex(3)
add_vertex(4)
add_vertex(5)


add_edge(1	,1	,1)
add_edge(2	,1	,1/4)
add_edge(2	,2	,1/4)
add_edge(2	,4, 1/4)
add_edge(2	,5	,1/4)
add_edge(3	,1	,1/3)
add_edge(3	,2	,1/3)
add_edge(3	,5	,1/3)
add_edge(4	,1	,1/2)
add_edge(4	,5	,1/2)
add_edge(5	,1	,1/3)
add_edge(5	,2	,1/3)
add_edge(5	,5	,1/3)










print_graph()
print("Internal representation: ", graph)

1  ->  1  edge weight:  1
2  ->  1  edge weight:  0.25
2  ->  2  edge weight:  0.25
2  ->  4  edge weight:  0.25
2  ->  5  edge weight:  0.25
3  ->  1  edge weight:  0.3333333333333333
3  ->  2  edge weight:  0.3333333333333333
3  ->  5  edge weight:  0.3333333333333333
4  ->  1  edge weight:  0.5
4  ->  5  edge weight:  0.5
5  ->  1  edge weight:  0.3333333333333333
5  ->  2  edge weight:  0.3333333333333333
5  ->  5  edge weight:  0.3333333333333333
Internal representation:  [[1, 0, 0, 0, 0], [0.25, 0.25, 0, 0.25, 0.25], [0.3333333333333333, 0.3333333333333333, 0, 0, 0.3333333333333333], [0.5, 0, 0, 0, 0.5], [0.3333333333333333, 0.3333333333333333, 0, 0, 0.3333333333333333]]


In [3]:
print(graph)

[[1, 0, 0, 0, 0], [0.25, 0.25, 0, 0.25, 0.25], [0.3333333333333333, 0.3333333333333333, 0, 0, 0.3333333333333333], [0.5, 0, 0, 0, 0.5], [0.3333333333333333, 0.3333333333333333, 0, 0, 0.3333333333333333]]


In [4]:
L2 = np.array(graph)
L = L2.transpose()
print(L)

[[1.         0.25       0.33333333 0.5        0.33333333]
 [0.         0.25       0.33333333 0.         0.33333333]
 [0.         0.         0.         0.         0.        ]
 [0.         0.25       0.         0.         0.        ]
 [0.         0.25       0.33333333 0.5        0.33333333]]


In [5]:
eVals, eVecs = la.eig(L)
order = np.absolute(eVals).argsort()[::-1]
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0]
100 * np.real(r / np.sum(r))

array([100.,   0.,   0.,   0.,   0.])

In [6]:
r = 100 * np.ones(5) / 5
r 

array([20., 20., 20., 20., 20.])

In [7]:
r = L @ r 
r 

array([48.33333333, 18.33333333,  0.        ,  5.        , 28.33333333])

In [8]:
r = 100 * np.ones(5) / 5
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = L @ r
    i += 1
print(str(i) + " iterations to convergence.")
r





21 iterations to convergence.


array([99.98647906,  0.00511198,  0.        ,  0.00189381,  0.00651515])

In [9]:
print(f'NumPy Array:\n{r}')

list1 = r.tolist()
print(f'List: {list1}')


NumPy Array:
[99.98647906  0.00511198  0.          0.00189381  0.00651515]
List: [99.98647906070494, 0.005111979991296032, 0.0, 0.0018938053348301395, 0.006515153968944105]


In [10]:
score = list1[4]
print(score)


0.006515153968944105


In [11]:
list1.append(score)

In [12]:


from csv import writer
  
 

  

with open('/content/sample3.csv', 'a') as f_object:
  
    
    writer_object = writer(f_object)
  
    
    writer_object.writerow(list1)

    f_object.close()

In [13]:
dataset = pd.read_csv("/content/sample3.csv")
dataset

Empty DataFrame
Columns: [99.98647906070494, 0.005111979991296032, 0.0, 0.0018938053348301395, 0.006515153968944105, 0.006515153968944105.1]
Index: []